### ISSUE TITLE
App is freezing after purchase

### ISSUE THREAD

**Issue by akardas16** [russell-archer/StoreHelperDemo#3] opened 2023-01-26 22:26 UTC
I have this issue both on real device and simulator. and there is no error. it is just freezing.

**Comment by russell-archer** [comment] 2023-01-26 23:33
Can you supply any more details because I can’t reproduce this on either the simulator or a real device. Is this a SwiftUI or UIKit app? Sent from my iPhoneOn 26 Jan 2023, at 22:26, Abdullah Kardaş ***@***.***> wrote:﻿
I have this issue both on real device and simulator. and there is no error. it is just freezing.

**Comment by akardas16** [comment] 2023-01-27 06:59
> Can you supply any more details because I can’t reproduce this on either the simulator or a real device. Is this a SwiftUI or UIKit app? Sent from my iPhoneOn 26 Jan 2023, at 22:26, Abdullah Kardaş ***@***.***> wrote:﻿ I have this issue both on real device and simulator. and there is no error. it is just freezing. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

it is happening in StoreHelperDemo app. I am using Xcode 14.2 and IOS 16.2 version. You should be able to reproduce it.
you can see it in the video https://drive.google.com/file/d/166lnrnR_XBqoxn7OVZmEX5f0jvromh_5/view?usp=share_link

**Comment by akardas16** [comment] 2023-01-27 08:55
I run it on mac and same thing happened I got QUARANTINED DUE TO HIGH LOGGING VOLUME error in console

**Comment by russell-archer** [comment] 2023-01-27 10:23
Ah yes, I see now. This may be relates to running on macOS Ventura 13.2. Are you running 13.2? I’ll look into it immediately!Sent from my iPhoneOn 27 Jan 2023, at 08:55, Abdullah Kardaş ***@***.***> wrote:﻿
I run it on mac and same thing happened I got QUARANTINED DUE TO HIGH LOGGING VOLUME error in console

**Comment by russell-archer** [comment] 2023-01-27 12:57
Hi Abdullah,

Thank you very much for reporting this. It turned out to be a nasty bug I had recently introduced while making “improvements”!

I was initially unable to reproduce the bug because I was testing it on an app that only had subscriptions and non-consumable products. When I used the StoreHelperDemo project I could indeed see that the app went into an infinite loop. It was caused by calls to StoreHelper.isPurchased() for a consumable product.

The bug is now fixed (in StoreHelper) and I’ve pushed the changes to GitHub.

I’m now adding automated testing as part of the release process so that this doesn’t happen again in the future!

Thanks again

Russell

**Closed as completed** 2023-01-27 13:00 UTC
